services:
  web:
    container_name: aimfornan_com
    image: nginx:mainline-alpine
    networks:
      - aimfornan_network
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  aimfornan_network:
    name: aimfornan_network
